// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU6gUkjgudjYRYZkEOH-fTK28qCjSwCiE',
    appId: '1:363932168351:web:723d2776f672b871c832aa',
    messagingSenderId: '363932168351',
    projectId: 'instagem-clone',
    authDomain: 'instagem-clone.firebaseapp.com',
    storageBucket: 'instagem-clone.appspot.com',
    measurementId: 'G-S016LH5QXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUA0HyK5-nCDcJOxwuCvqxoof72JGfYFw',
    appId: '1:363932168351:android:45fb31a76024cd9ac832aa',
    messagingSenderId: '363932168351',
    projectId: 'instagem-clone',
    storageBucket: 'instagem-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzDKQxMr2kuwfQ38i33Sh1C5MAs8MNEzc',
    appId: '1:363932168351:ios:cdd72590e6989efec832aa',
    messagingSenderId: '363932168351',
    projectId: 'instagem-clone',
    storageBucket: 'instagem-clone.appspot.com',
    iosBundleId: 'com.example.loginTokenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzDKQxMr2kuwfQ38i33Sh1C5MAs8MNEzc',
    appId: '1:363932168351:ios:cdd72590e6989efec832aa',
    messagingSenderId: '363932168351',
    projectId: 'instagem-clone',
    storageBucket: 'instagem-clone.appspot.com',
    iosBundleId: 'com.example.loginTokenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU6gUkjgudjYRYZkEOH-fTK28qCjSwCiE',
    appId: '1:363932168351:web:50bee1edbb30ad04c832aa',
    messagingSenderId: '363932168351',
    projectId: 'instagem-clone',
    authDomain: 'instagem-clone.firebaseapp.com',
    storageBucket: 'instagem-clone.appspot.com',
    measurementId: 'G-RK0Q85N8BK',
  );

}