// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlIUr4CgN9sdLAYuTi9JdJidiMHCksbVU',
    appId: '1:650386375386:web:db09b51f67a2f6a1a95be3',
    messagingSenderId: '650386375386',
    projectId: 'instagram-b3526',
    authDomain: 'instagram-b3526.firebaseapp.com',
    storageBucket: 'instagram-b3526.appspot.com',
    measurementId: 'G-WPWNMZ9K93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZmY43AUah39-Yq1ZfA_iQugBl4R3a6M',
    appId: '1:650386375386:android:bec52c251b13a7bfa95be3',
    messagingSenderId: '650386375386',
    projectId: 'instagram-b3526',
    storageBucket: 'instagram-b3526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_oM5pLT8JSYuxdKABluCMcNGzvHZ9gk',
    appId: '1:650386375386:ios:55773ca1fda47249a95be3',
    messagingSenderId: '650386375386',
    projectId: 'instagram-b3526',
    storageBucket: 'instagram-b3526.appspot.com',
    iosBundleId: 'com.example.loginTokenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_oM5pLT8JSYuxdKABluCMcNGzvHZ9gk',
    appId: '1:650386375386:ios:55773ca1fda47249a95be3',
    messagingSenderId: '650386375386',
    projectId: 'instagram-b3526',
    storageBucket: 'instagram-b3526.appspot.com',
    iosBundleId: 'com.example.loginTokenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlIUr4CgN9sdLAYuTi9JdJidiMHCksbVU',
    appId: '1:650386375386:web:a3b5998e6bc3ff69a95be3',
    messagingSenderId: '650386375386',
    projectId: 'instagram-b3526',
    authDomain: 'instagram-b3526.firebaseapp.com',
    storageBucket: 'instagram-b3526.appspot.com',
    measurementId: 'G-VK45GLVNZK',
  );
}
